#!/bin/bash

case "$1" in

install)  echo "Install Gems"
    sudo apt-get update
    sudo apt-get install curl vim-nox -y
    curl -L https://www.opscode.com/chef/install.sh | sudo bash
    sudo chef-client -z -o ssh_test::install_metal
    ;;
both)  echo  "Both Machines"
    sudo chef-client -z -o ssh_test::both
    ;;
clean)  echo  "Deleting Nodes and Clients"
    rm -rf clients/*
    rm -rf nodes/*
    ;;
*) echo "der der der"
   ;;
esac
