#!/bin/bash

CHEF_CLIENT=`which chef-client`

case "$1" in

install_local)  echo "Install Gems"
    sudo apt-get update
    sudo apt-get install curl vim-nox -y
    if [ -z $CHEF_CLIENT ]
    then
      curl -L https://www.opscode.com/chef/install.sh | sudo bash
    fi
    sudo chef-client -z -o ssh_test::install_metal_local
    ;;
install_rubygems)  echo "Install Gems"
    sudo apt-get update
    sudo apt-get install curl vim-nox -y
    if [ -z $CHEF_CLIENT ]
    then
      curl -L https://www.opscode.com/chef/install.sh | sudo bash
    fi
    sudo chef-client -z -o ssh_test::install_metal_rubygems
    ;;
both)  echo  "Both Machines"
    sudo chef-client -z -o ssh_test::both
    ;;
clean)  echo  "Deleting Nodes and Clients"
    rm -rf clients/*
    rm -rf nodes/*
    ;;
*) echo "der der der"
   ;;
esac
